"""Flow past a cylinder, measured rather than simulated.

Every other dataset in this repository is generated by the same finite-element
code that supplies the learner's operator.  That is convenient and it is exactly
what an inverse-crime objection is about.  This one is not: it is particle-image
velocimetry of water flowing past a physical cylinder, taken from RealPDEBench,
and nothing here produced it.

The geometry is a real object.  A cylinder sits in the channel and the fluid goes
around it, so the tensor's spatial mode indexes a domain with a hole in it --
the same structure as the synthetic ``plane_domain`` family, with the difference
that neither the field nor the boundary was chosen by us.

Three things follow that make this the cleanest test in the repository:

- the learner's operator cannot be the generator of the data, because the data
  came from a laboratory;
- the governing equations are Navier-Stokes at Reynolds numbers from 1 875 to
  11 625, not the diffusion or shallow-water operators used elsewhere, so the
  operator prior is knowingly wrong about the physics and right only about the
  geometry;
- there is no credible operator for the time axis, so the temporal factor is a
  free table.  The comparison is then purely about the spatial function space,
  which is what the paper claims.
"""

from __future__ import annotations

import hashlib
import math
from pathlib import Path

import numpy as np
import torch
from scipy.spatial import Delaunay

from .bases import BasisSpec
from .joint_diffusion_2d import GroupedFieldDataset
from .operator_diagnostics import (mass_orthonormalize_columns,
                                   sparse_eigenpairs)
from .simplex_fem import SimplexMesh, assemble_sparse

SOURCE = Path("/mnt/data/xuangu-fang/ai-physical-dynamics/datasets/"
              "realpde_cylinder_fresh_locked/locked_r64.npz")

# Grid geometry of the released tensor: 32 x 64 cells, square, so the channel is
# a little over two units long and one unit high.
N_ROWS, N_COLS = 32, 64
SPACING = 1. / (N_ROWS - 1)


def locate_cylinder(speed: np.ndarray, quantile: float = .02
                    ) -> tuple[float, float, float]:
    """Centre and radius of the obstacle, in grid units.

    The rule is stated rather than eyeballed: take the cells whose
    time-averaged speed falls in the lowest ``quantile`` of the field, and fit
    the disc that covers them.  On this data the radial profile leaves little
    room for argument -- mean speed is `0.088` inside three cells of the centre
    and `0.198` beyond six -- and the answer is a disc of radius about four
    cells at row 16.6, column 22.1.

    In a deployment the position of one's own apparatus is simply known; the
    rule exists so that the number in the metadata can be audited rather than
    trusted, and :func:`cylinder_flow_tensor` re-derives it from the observed
    entries alone when asked.
    """
    rows, columns = np.mgrid[0:speed.shape[0], 0:speed.shape[1]]
    inside = speed <= np.quantile(speed[np.isfinite(speed)], quantile)
    centre_row = float(rows[inside].mean())
    centre_column = float(columns[inside].mean())
    radius = float(np.sqrt((rows[inside] - centre_row) ** 2
                           + (columns[inside] - centre_column) ** 2).max())
    return centre_row, centre_column, radius


def _grid_coordinates() -> torch.Tensor:
    rows, columns = np.mgrid[0:N_ROWS, 0:N_COLS]
    return torch.from_numpy(
        np.stack([columns.ravel(), rows.ravel()], axis=1) * SPACING).double()


def _triangulate(points: torch.Tensor, drop_inside=None) -> SimplexMesh:
    """Delaunay over the given nodes, optionally discarding cells in a region.

    With ``drop_inside`` the mesh respects the obstacle; without it the same
    nodes are connected straight across it.  That single difference is the whole
    ablation, and it is applied to an identical node set.
    """
    numpy_points = points.double().numpy()
    cells = Delaunay(numpy_points).simplices
    if drop_inside is not None:
        centroids = numpy_points[cells].mean(axis=1)
        cells = cells[~drop_inside(centroids)]
    return SimplexMesh(points.double(),
                       torch.from_numpy(cells.astype(np.int64)), "triangles")


def _flat_chart_basis(coordinates: torch.Tensor, mass, count: int):
    low = coordinates.min(0).values.double()
    span = (coordinates.max(0).values.double() - low).clamp_min(1e-9)
    scaled = (coordinates.double() - low) / span
    limit = int(math.ceil(math.sqrt(count))) + 3
    pairs = torch.cartesian_prod(torch.arange(limit), torch.arange(limit))
    pairs = pairs[torch.argsort((pairs.double() ** 2).sum(1), stable=True)[:count]]
    columns = (torch.cos(math.pi * scaled[:, 0:1] * pairs[:, 0].double())
               * torch.cos(math.pi * scaled[:, 1:2] * pairs[:, 1].double()))
    return mass_orthonormalize_columns(columns, mass), (pairs.double() ** 2).sum(1)


def cylinder_flow_tensor(*, source: Path = SOURCE, channel: int = 0,
                         n_time: int = 48, time_start: int = 200,
                         basis_cutoff: int = 16, quantile: float = .02,
                         margin: float = .0, permutation_seed: int = 9173
                         ) -> GroupedFieldDataset:
    """``Y(simulation, time, node)`` for measured flow past a cylinder.

    ``channel`` selects a velocity component.  Time is subsampled from the
    stationary part of each record; ``time_start`` skips the startup transient.
    """
    payload = np.load(source)
    fields = payload["locked_fields"]                    # (sims, T, 2, 32, 64)
    reynolds = payload["locked_reynolds"]
    speed = np.sqrt((fields ** 2).sum(2)).mean(axis=(0, 1))
    centre_row, centre_column, radius = locate_cylinder(speed, quantile)

    coordinates = _grid_coordinates()
    centre = torch.tensor([centre_column, centre_row], dtype=torch.float64) * SPACING
    physical_radius = (radius + margin) * SPACING
    outside = (coordinates - centre).norm(dim=1) > physical_radius
    kept = torch.where(outside)[0]
    nodes = coordinates[kept]

    def inside_cylinder(points: np.ndarray) -> np.ndarray:
        offset = points - centre.numpy()[None, :]
        return np.linalg.norm(offset, axis=1) <= physical_radius

    aware_mesh = _triangulate(nodes, drop_inside=inside_cylinder)
    blind_mesh = _triangulate(nodes)
    aware_stiffness, mass = assemble_sparse(aware_mesh, 1.)
    blind_stiffness, blind_mass = assemble_sparse(blind_mesh, 1.)

    times = np.linspace(time_start, fields.shape[1] - 1, n_time).astype(int)
    values = torch.from_numpy(
        fields[:, times, channel].reshape(len(fields), n_time, -1)).double()
    values = values[:, :, kept]
    values = (values - values.mean()) / values.std().clamp_min(1e-12)

    aware_values, aware_basis = sparse_eigenpairs(aware_stiffness, mass,
                                                  basis_cutoff)
    blind_values, blind_basis = sparse_eigenpairs(blind_stiffness, blind_mass,
                                                  basis_cutoff)
    chart_basis, chart_values = _flat_chart_basis(nodes, mass, basis_cutoff)
    permutation = torch.randperm(
        len(kept), generator=torch.Generator().manual_seed(permutation_seed))

    scale = math.pi ** 2
    spatial = {
        "geometry_operator": (aware_basis, aware_values / scale),
        "blind_operator": (blind_basis, blind_values / scale),
        "flat_chart": (chart_basis, chart_values[:chart_basis.shape[1]]),
        "permuted": (aware_basis[permutation], aware_values / scale),
    }
    matrices = {"coordinates": nodes.float()}
    for name, (basis, eigenvalues) in spatial.items():
        matrices[f"{name}_basis"] = basis.float()
        matrices[f"{name}_eigenvalues"] = eigenvalues[:basis.shape[1]].float()

    metadata = {
        "family": "cylinder_flow", "layout": "measured",
        "source": str(source),
        "provenance": "RealPDEBench cylinder/real (particle-image velocimetry)",
        "generated_by_this_repository": False,
        "pde": "incompressible Navier-Stokes past a circular cylinder",
        "reynolds_numbers": [float(v) for v in reynolds],
        "tensor_semantics": "simulation x time x node",
        "channel": int(channel), "time_indices": times.tolist(),
        "cylinder_centre_grid": [centre_row, centre_column],
        "cylinder_radius_grid": radius,
        "cylinder_rule": f"cells below the {quantile:.0%} quantile of "
                         "time-averaged speed, covered by a disc",
        "grid": [N_ROWS, N_COLS], "spacing": SPACING,
        "n_nodes": int(len(kept)), "n_removed_by_cylinder": int(len(coordinates) - len(kept)),
        "mesh_hash": aware_mesh.hash(), "blind_mesh_hash": blind_mesh.hash(),
        "operator_information_tier":
            "geometry only (obstacle known; the governing equations are not the "
            "operator the learner uses)",
        "time_factor": "free table: no credible operator for the time axis",
        "basis_cutoff": int(basis_cutoff),
        "checksum": hashlib.sha256(values.numpy().tobytes()).hexdigest()[:16],
        "coordinate_groups": [[0], [1], [2]],
    }
    specs = tuple(BasisSpec("neumann", max(1, basis_cutoff - 1), name)
                  for name in ("simulation", "time", "node"))
    return GroupedFieldDataset(
        f"cylinder_flow_c{channel}_t{n_time}_k{basis_cutoff}", values.float(),
        ("simulation", "time", "node"), specs, (False, False, False),
        f"external:{source.name}",
        "Measured velocity of flow past a cylinder; the spatial mode indexes a "
        "channel with a physical obstacle removed from it.",
        metadata=metadata, groups=((0,), (1,), (2,)), operator_matrices=matrices)
